ALTER TABLE url_hits
    ADD COLUMN IF NOT EXISTS utm_source TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS utm_medium TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS utm_campaign TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS utm_term TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS utm_content TEXT NOT NULL DEFAULT '';
