port 0
tls-port 6379
tls-cert-file /run/secrets/account-access-tls.crt
tls-key-file /run/secrets/account-access-tls.key
tls-ca-cert-file /run/secrets/account-access-ca.crt
tls-auth-clients yes

aclfile /run/secrets/account-access-users.acl
protected-mode yes

appendonly yes
appendfsync always
no-appendfsync-on-rewrite no
maxmemory-policy noeviction

save 900 1
save 300 10
save 60 10000
