#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

SKYMAIL_CLIENT_ID="${SKYMAIL_CLIENT_ID:-skymail}"
CORE_CLIENT_ID="${CORE_CLIENT_ID:-${KEYCLOAK_CLIENT_ID:-core}}"
SKYMAIL_LIST_ROLES="skymail:access skymail:lists:read skymail:lists:write"
KEYCLOAK_ADMIN_URL_DEFAULT="https://e.yildizskylab.com"
KEYCLOAK_REALM_DEFAULT="e-skylab"
GRANT_OK=0
AUD_OK=0
ROLES_OK=0

_load_kc_env() {
  local f line key val
  for f in "${ENV_FILE}" .env ../core-backend/.env ../core-backend-event-mail/.env; do
    [[ -f "$f" ]] || continue
    while IFS= read -r line || [[ -n "$line" ]]; do
      case "$line" in
        KEYCLOAK_URL=*|KEYCLOAK_REALM=*|KEYCLOAK_CLIENT_ID=*|KEYCLOAK_CLIENT_SECRET=*|SKYMAIL_URL=*)
          key=${line%%=*}
          val=${line#*=}
          val=${val%$'\r'}
          if [[ -z "${!key:-}" && -n "$val" ]]; then
            printf -v "$key" '%s' "$val"
          fi
          ;;
      esac
    done < "$f"
  done
}

grant_via_admin() {
  python3 - "$SKYMAIL_CLIENT_ID" "$CORE_CLIENT_ID" $SKYMAIL_LIST_ROLES <<'PY'
import json, os, sys, urllib.error, urllib.parse, urllib.request

skymail_client, core_client, *want_roles = sys.argv[1:]
base = os.environ.get("KEYCLOAK_URL", "").strip().rstrip("/")
realm = os.environ.get("KEYCLOAK_REALM", "").strip()
if "/realms/" in base:
    host, rest = base.split("/realms/", 1)
    base = host
    if not realm:
        realm = rest.split("/", 1)[0]
if not realm:
    realm = "e-skylab"
cid = os.environ.get("KEYCLOAK_CLIENT_ID", "").strip() or core_client
secret = os.environ.get("KEYCLOAK_CLIENT_SECRET", "").strip()
if not base or not cid or not secret:
    print("SKIP no KEYCLOAK_URL/CLIENT_ID/SECRET")
    sys.exit(2)

def call(method, url, token=None, form=None, data=None, expect=None):
    headers = {}
    body = None
    if form is not None:
        body = urllib.parse.urlencode(form).encode()
        headers["Content-Type"] = "application/x-www-form-urlencoded"
    elif data is not None:
        body = json.dumps(data).encode()
        headers["Content-Type"] = "application/json"
    if token:
        headers["Authorization"] = "Bearer " + token
    req = urllib.request.Request(url, data=body, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req) as resp:
            raw = resp.read()
            status = resp.status
            payload = json.loads(raw) if raw else None
    except urllib.error.HTTPError as e:
        raw = e.read()
        status = e.code
        try:
            payload = json.loads(raw) if raw else None
        except json.JSONDecodeError:
            payload = None
    if expect is not None and status not in expect:
        print(f"HTTP {status} {method} {url.split('?')[0]}", file=sys.stderr)
        sys.exit(1)
    return status, payload

_, tok = call(
    "POST",
    f"{base}/realms/{realm}/protocol/openid-connect/token",
    form={
        "grant_type": "client_credentials",
        "client_id": cid,
        "client_secret": secret,
        "scope": "openid",
    },
    expect=(200,),
)
token = tok["access_token"]

def client_uuid(client_id):
    _, rows = call(
        "GET",
        f"{base}/admin/realms/{realm}/clients?clientId={urllib.parse.quote(client_id)}",
        token=token,
        expect=(200,),
    )
    if not rows:
        print(f"missing client {client_id}", file=sys.stderr)
        sys.exit(1)
    return rows[0]["id"]

sky_uuid = client_uuid(skymail_client)
core_uuid = client_uuid(core_client)
_, sa = call(
    "GET",
    f"{base}/admin/realms/{realm}/clients/{core_uuid}/service-account-user",
    token=token,
    expect=(200,),
)
sa_id = sa["id"]

roles = []
for name in want_roles:
    status, role = call(
        "GET",
        f"{base}/admin/realms/{realm}/clients/{sky_uuid}/roles/{urllib.parse.quote(name)}",
        token=token,
    )
    if status == 404:
        _, role = call(
            "POST",
            f"{base}/admin/realms/{realm}/clients/{sky_uuid}/roles",
            token=token,
            data={"name": name},
            expect=(201, 204, 409),
        )
        _, role = call(
            "GET",
            f"{base}/admin/realms/{realm}/clients/{sky_uuid}/roles/{urllib.parse.quote(name)}",
            token=token,
            expect=(200,),
        )
    elif status != 200:
        print(f"role {name} status {status}", file=sys.stderr)
        sys.exit(1)
    roles.append({"id": role["id"], "name": role["name"]})

call(
    "POST",
    f"{base}/admin/realms/{realm}/users/{sa_id}/role-mappings/clients/{sky_uuid}",
    token=token,
    data=roles,
    expect=(204, 200),
)

_, mappers = call(
    "GET",
    f"{base}/admin/realms/{realm}/clients/{core_uuid}/protocol-mappers/models",
    token=token,
    expect=(200,),
)
have_aud = False
for m in mappers or []:
    cfg = m.get("config") or {}
    if m.get("protocolMapper") == "oidc-audience-mapper" and cfg.get("included.client.audience") == skymail_client:
        have_aud = True
        break
if not have_aud:
    call(
        "POST",
        f"{base}/admin/realms/{realm}/clients/{core_uuid}/protocol-mappers/models",
        token=token,
        data={
            "name": "aud-skymail",
            "protocol": "openid-connect",
            "protocolMapper": "oidc-audience-mapper",
            "config": {
                "included.client.audience": skymail_client,
                "id.token.claim": "false",
                "access.token.claim": "true",
            },
        },
        expect=(201, 204, 409),
    )
    have_aud = True

_, tok2 = call(
    "POST",
    f"{base}/realms/{realm}/protocol/openid-connect/token",
    form={
        "grant_type": "client_credentials",
        "client_id": cid,
        "client_secret": secret,
        "scope": "openid",
    },
    expect=(200,),
)
parts = tok2["access_token"].split(".")
pad = "=" * (-len(parts[1]) % 4)
import base64
claims = json.loads(base64.urlsafe_b64decode(parts[1] + pad))
aud = claims.get("aud")
sky_roles = ((claims.get("resource_access") or {}).get(skymail_client) or {}).get("roles") or []
missing = [r for r in want_roles if r not in sky_roles]
print("aud=" + json.dumps(aud, ensure_ascii=False))
print("skymail_roles=" + json.dumps(sorted(sky_roles), ensure_ascii=False))
if missing:
    print("missing_roles=" + json.dumps(missing, ensure_ascii=False))
    sys.exit(1)
if have_aud:
    print("audience_mapper=ok")
if isinstance(aud, str):
    auds = [aud]
elif isinstance(aud, list):
    auds = aud
else:
    auds = []
if skymail_client not in auds:
    print("missing_aud=" + skymail_client)
    sys.exit(3)
print("GRANT_OK")
PY
}

_load_kc_env
KEYCLOAK_URL="${KEYCLOAK_URL:-$KEYCLOAK_ADMIN_URL_DEFAULT}"
KEYCLOAK_REALM="${KEYCLOAK_REALM:-$KEYCLOAK_REALM_DEFAULT}"
CORE_CLIENT_ID="${CORE_CLIENT_ID:-${KEYCLOAK_CLIENT_ID:-core}}"

banner "Core → Skymail lists"

stage "Grant via Keycloak admin API"
say "Skymail hardcodes client id skymail. POST /v1/mailing_lists needs skymail:access plus skymail:lists:write; GET recipients needs skymail:lists:read."
say "Core S2S token is client-credentials for the core confidential client. resource_access.skymail must carry those roles; aud must include skymail, not only core."
say "Default Skymail API origin is https://api.yildizskylab.com/api/skymail + /v1/mailing_lists. Internal SKYMAIL_URL may be http://skymail-app:3000. Do not point SKYMAIL_URL at core."
if [[ -n "${KEYCLOAK_CLIENT_SECRET:-}" ]]; then
  note "KEYCLOAK_CLIENT_ID=${CORE_CLIENT_ID} realm=${KEYCLOAK_REALM} — trying admin API (secrets not printed)."
  if grant_out=$(grant_via_admin); then
    GRANT_OK=1
    ROLES_OK=1
    AUD_OK=1
    say "$grant_out"
    note "Core SA now has skymail list roles and an aud-skymail mapper. Restart core so it fetches a new token."
  else
    status=$?
    warn "admin API grant failed (exit ${status}). Continue with the console clicks."
  fi
else
  warn "KEYCLOAK_CLIENT_SECRET is not in the environment. Console clicks next; or re-run with core's KEYCLOAK_* env."
fi
pause "Continue?"

stage "skymail list roles exist"
open_url "${KEYCLOAK_URL%/}/admin/master/console/#/${KEYCLOAK_REALM}/clients"
step "Realm is ${KEYCLOAK_REALM}. Open Clients → skymail (client id skymail) → Roles."
step "Confirm these client roles exist (create only if missing; they are not realm roles):"
step "  skymail:access"
step "  skymail:lists:read"
step "  skymail:lists:write"
step "Keep skymail:mails:write if welcome or certificate mail already works. Do not create a second IdP or a new confidential client."
if [[ "$ROLES_OK" -eq 1 ]]; then
  note "Admin API already saw these roles on skymail."
fi
pause "List roles are on skymail?"

stage "Core service account mapping"
open_url "${KEYCLOAK_URL%/}/admin/master/console/#/${KEYCLOAK_REALM}/clients"
step "Open the ${CORE_CLIENT_ID} client → Service accounts roles (or Users → service-account-${CORE_CLIENT_ID})."
step "Assign client roles: Filter by client = skymail."
step "Roles: skymail:access, skymail:lists:read, skymail:lists:write."
step "If Full scope allowed is OFF on ${CORE_CLIENT_ID}, also add the skymail client to its optional/default client scopes so resource_access.skymail appears on the token."
if [[ "$GRANT_OK" -eq 1 ]]; then
  note "Admin API already posted those role mappings onto the ${CORE_CLIENT_ID} service account."
fi
pause "lists:read and lists:write assigned to core?"

stage "Audience mapper for skymail"
open_url "${KEYCLOAK_URL%/}/admin/master/console/#/${KEYCLOAK_REALM}/clients"
step "Open ${CORE_CLIENT_ID} → Client scopes → ${CORE_CLIENT_ID}-dedicated → Add mapper → By configuration → Audience."
step "Name: aud-skymail. Included Client Audience = skymail. Add to access token = ON. Add to ID token = OFF. Save."
step "Without this, the S2S token often has aud=core (or account) only; Skymail may still 403 even after roles exist."
if [[ "$AUD_OK" -eq 1 ]]; then
  note "Admin API already added the oidc-audience-mapper included.client.audience=skymail."
fi
step "Restart core (it caches the client-credentials token). Then POST /v1/events/{id}/mail-list should be 200, not 500 wrapping a Skymail 403."
pause "Mapper saved and core restarted?"

finish
